disabled_rules:
  - line_length
opt_in_rules: # some rules are only opt-in
  - missing_docs
included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Tests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Packages
