dist: trusty
language: swift
matrix:
    include:
        - os: linux
          language: generic
          sudo: required
        - os: osx
          osx_image: xcode8
install:
- curl -sL https://gist.github.com/kylef/5c0475ff02b7c7671d2a/raw/621ef9b29bbb852fdfd2e10ed147b321d792c1e4/swiftenv-install.sh | bash
script:
- . ~/.swiftenv/init
- swift build
