dist: trusty
language: swift
matrix:
  include:
    # - os: linux
    #   language: generic
    #   sudo: required
    # disable linux temporary
    - os: osx
      osx_image: xcode8.1
env:
  global:
    - SWIFT_VERSION=3.0.1
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
script:
  - swift test
